#!/usr/bin/env bash

# Pre-commit script to ensure the required IBM/Instana
# license headers are added to the relevant source files.
# Note that if you bypass this pre-commit git hook and didn't
# run the maven command mentioned below to add the license headers
# to new files, the build will fail.

echo
echo Running "${BASH_SOURCE[0]}"
echo

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

command_exists mvn || {
	echo >&2 "Can't find 'mvn' in PATH. Please ensure you have installed Maven."
	exit 1
}

echo "Updating license headers where necessary..."
if mvn --quiet validate license:format; then
	echo "Successfully updated license headers"
else
	echo >&2 "Failed to update license headers, please check the output of 'mvn validate license:format' to see what's wrong and rectify"
	exit 1
fi
