#
# (c) Copyright IBM Corp. 2025
#
version: "2"

tasks:
  pr-code-checks:
    displayName: promote-artifacts
    runtimeClassName: x86-xlarge
    onError: stopAndFail
    include:
      - dind
    steps:
      - name: unit-test
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          source $WORKSPACE/$APP_REPO_FOLDER/ci/sps-scripts/fedramp-promotion.sh
      - name: detect-secrets
        include:
          - docker-socket
  code-pr-finish:
    steps:
      - name: evaluate
        when: 'false'
      - name: prepare
        when: 'false'
      - name: run-stage
        when: 'false'
