linters-settings:
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - goimports
    - gosimple
    - govet
    - ineffassign
    - unused
    - misspell
    - exhaustive
    - errcheck

service:
  golangci-lint-version: 1.56.2 # use the fixed version to not introduce new linters unexpectedly

