linters-settings:
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
  - goimports
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - typecheck
  - unused
  - misspell

service:
  golangci-lint-version: 1.58.x # use the fixed version to not introduce new linters unexpectedly

