# TODO: review linters
# TODO: add to pipeline for branch
# TODO: add crd and code gen for prs
linters-settings:
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - misspell
    - exhaustive

service:
  golangci-lint-version: 1.31.x # use the fixed version to not introduce new linters unexpectedly

