#
# (c) Copyright IBM Corp. 2025
#
version: '2'

tasks:
  simple-execute:
    displayName: "e2e-test"
    include:
      - dind
    steps:
    - name: execute
      include:
        - docker-socket
      script: |
        #!/usr/bin/env bash
        echo "Hello from e2e"

        "Triggering async e2e tasks"
        # source "${ONE_PIPELINE_PATH}"/tools/trigger-task

        RUN_GKE_LATEST=$(get_env run-gke-latest)
        echo "run-gke-latest: $RUN_GKE_LATEST"
        export_env RUN_GKE_LATEST
        # TODO: add conditional triggering

        trigger-task e2e-gke-latest
        trigger-task e2e-gke-lowest
        trigger-task e2e-ocp-latest
        trigger-task e2e-ocp-lowest

e2e-gke-latest:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
  script: |
    #!/usr/bin/env bash
    Hello from e2e-gke-latest!
    env

e2e-gke-lowest:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
  script: |
    #!/usr/bin/env bash
    Hello from e2e-gke-lowest!
    env

e2e-ocp-latest:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
  script: |
    #!/usr/bin/env bash
    Hello from e2e-ocp-latest!
    env

e2e-ocp-lowest:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
  script: |
    #!/usr/bin/env bash
    Hello from e2e-ocp-lowest!
    env
