#
# (c) Copyright IBM Corp. 2025
#
version: '2'

tasks:
  simple-execute:
    displayName: "e2e-test"
    include:
      - dind
    steps:
    - name: execute
      include:
        - docker-socket
      script: |
        #!/usr/bin/env bash
        echo "Hello from e2e"
        env
        echo "==== trigger payload ===="
        cat "${TRIGGER_PAYLOAD_PATH}"
        echo "==== done ===="
        echo pwd
        echo ls -lah
        RUN_GKE_LATEST=$(get_env run-gke-latest)
        echo "run-gke-latest: $RUN_GKE_LATEST"
        set_env pipeline-config ".pipeline-config-e2e-stages-v1.yaml"
        export_env RUN_GKE_LATEST
        # TODO: add conditional triggering

        trigger-task e2e-gke-latest
        trigger-task e2e-gke-lowest
        trigger-task e2e-ocp-latest
        trigger-task e2e-ocp-lowest
