#
# (c) Copyright IBM Corp. 2025
#
my-custom-task:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.12@sha256:ff4053b0bca784d6d105fee1d008cfb20db206011453071e86b69ca3fde706a4
  script: |
    #!/usr/bin/env bash
    if [[ "$PIPELINE_DEBUG" == 1 ]]; then
      trap env EXIT
      env
      set -x
    fi
    printf "Test custom stage to trigger async"
    list_repos
    list_artifacts
    get_env "variable-for-my-custom-task"

e2e-gke-latest:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
  dind: true
  script: |
    #!/usr/bin/env bash
    Hello from e2e-gke-latest!
    env

e2e-gke-lowest:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
  dind: true
  script: |
    #!/usr/bin/env bash
    Hello from e2e-gke-lowest!
    env

e2e-ocp-latest:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
  dind: true
  script: |
    #!/usr/bin/env bash
    Hello from e2e-ocp-latest!
    env

e2e-ocp-lowest:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
  dind: true
  script: |
    #!/usr/bin/env bash
    Hello from e2e-gke-lowest!
    env

my-custom-task:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.12@sha256:ff4053b0bca784d6d105fee1d008cfb20db206011453071e86b69ca3fde706a4
  script: |
    #!/usr/bin/env bash
    if [[ "$PIPELINE_DEBUG" == 1 ]]; then
      trap env EXIT
      env
      set -x
    fi
    printf "Test custom stage to trigger async"
    list_repos
    list_artifacts
    get_env "variable-for-my-custom-task"