#
# (c) Copyright IBM Corp. 2025
#
e2e-gke-latest:
  script: |
    #!/usr/bin/env bash
    Hello from e2e-gke-latest!
    env

e2e-gke-lowest:
  script: |
    #!/usr/bin/env bash
    Hello from e2e-gke-lowest!
    env

e2e-ocp-latest:
  script: |
    #!/usr/bin/env bash
    Hello from e2e-ocp-latest!
    env

e2e-ocp-lowest:
  script: |
    #!/usr/bin/env bash
    Hello from e2e-gke-lowest!
    env
