tasks:
  pr-code-checks:
    displayName: verify-latest-release
    runtimeClassName: large
    runAfter: 
      - pr-code-checks
    include:
      - dind
    steps:
      - name: unit-test
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
        include:
          - docker-socket
        script: |
            #!/usr/bin/env bash
            $WORKSPACE/$APP_REPO_FOLDER/ci/scripts/olm-release-pr-creation.sh
      - name: detect-secrets
        include:
          - docker-socket

  pr-code-checks-1:
    displayName: redhat-marketplace-operator-commit-changes-and-create-pr
    runtimeClassName: large
    runAfter: 
      - pr-code-checks
    include:
      - dind
    steps:
      - name: unit-test
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
        include:
          - docker-socket
        script: |
            #!/usr/bin/env bash
            $WORKSPACE/$APP_REPO_FOLDER/ci/scripts/commit-changes-to-public-repo.sh
      - name: detect-secrets
        include:
          - docker-socket
  
  pr-code-checks-2:
    from: pr-code-checks
    displayName: redhat-marketplace-operators-rebase
    runtimeClassName: large
    runAfter: 
      - pr-code-checks
    include:
      - dind
    steps:
      - name: unit-test
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
        include:
          - docker-socket
        script: |
            #!/usr/bin/env bash
            $WORKSPACE/$APP_REPO_FOLDER/ci/scripts/rebase-fork-branches.sh
      - name: detect-secrets
        include:
          - docker-socket
  
  pr-code-checks-3:
    from: pr-code-checks
    displayName: community-operators-rebase
    runtimeClassName: large
    runAfter: 
      - pr-code-checks
    include:
      - dind
    steps:
      - name: unit-test
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
        include:
          - docker-socket
        script: |
            #!/usr/bin/env bash
            $WORKSPACE/$APP_REPO_FOLDER/ci/scripts/rebase-fork-branches.sh
      - name: detect-secrets
        include:
          - docker-socket
    
  pr-code-checks-4:
    from: pr-code-checks
    displayName: certified-operators-rebase
    runtimeClassName: large
    runAfter: 
      - pr-code-checks
    include:
      - dind
    steps:
      - name: unit-test
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
        include:
          - docker-socket
        script: |
            #!/usr/bin/env bash
            $WORKSPACE/$APP_REPO_FOLDER/ci/scripts/rebase-fork-branches.sh
      - name: detect-secrets
        include:
          - docker-socket

  pr-code-checks-5:
    from: pr-code-checks
    displayName: certified-operators-commit-changes-and-create-pr
    runtimeClassName: large
    runAfter: 
      - pr-code-checks
    include:
      - dind
    steps:
      - name: unit-test
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
        include:
          - docker-socket
        script: |
            #!/usr/bin/env bash
            $WORKSPACE/$APP_REPO_FOLDER/ci/scripts/commit-changes-to-public-repo.sh
      - name: detect-secrets
        include:
          - docker-socket
    
  pr-code-checks-6:
    from: pr-code-checks
    displayName: community-operators-commit-changes-and-create-pr
    runtimeClassName: large
    runAfter: 
      - pr-code-checks
    include:
      - dind
    steps:
      - name: unit-test
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
        include:
          - docker-socket
        script: |
            #!/usr/bin/env bash
            $WORKSPACE/$APP_REPO_FOLDER/ci/scripts/commit-changes-to-public-repo.sh
      - name: detect-secrets
        include:
          - docker-socket