FROM registry.access.redhat.com/ubi7/ubi-minimal:latest
MAINTAINER Instana, support@instana.com

LABEL name="instana-agent-operator" \
      vendor="Instana" \
      version="v0.0.1" \
      release="1" \
      summary="Experimental alpha version of the upcoming Kubernetes Operator for the Instana APM Agent" \
      description="This operator will deploy a daemon set to run the Instana APM Agent on each cluster node."

COPY licenses /licenses

WORKDIR /work/
COPY target/*-runner /work/instana-agent-operator
RUN chmod 775 /work

EXPOSE 8080
CMD ["./instana-agent-operator"]
