apiVersion: v1
kind: ServiceAccount
metadata:
  name: instana-operator
  namespace: instana-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: instana-operator
  namespace: instana-agent
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - pods
  - pods/exec
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: instana-operator
  namespace: instana-agent
subjects:
- kind: ServiceAccount
  name: instana-operator
  namespace: instana-agent
roleRef:
  kind: ClusterRole
  name: instana-operator
  apiGroup: rbac.authorization.k8s.io
