apiVersion: v1
kind: ServiceAccount
metadata:
  name: instana-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: instana-operator
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - pods
  - pods/exec
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: instana-operator
subjects:
- kind: ServiceAccount
  name: instana-operator
  namespace: default # the namespace the operator is deployed in
roleRef:
  kind: ClusterRole
  name: instana-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: instana-operator
spec:
  selector:
    matchLabels:
      app: instana-operator
  replicas: 2
  template:
    metadata:
      labels:
        app: instana-operator
    spec:
      serviceAccountName: instana-operator
      containers:
      - image: instana/instana-operator
        name: instana-operator
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
kind: Service
apiVersion: v1
metadata:
  name: instana-operator
spec:
  selector:
    app: instana-operator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
