resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: instana/instana-agent-operator
  newName: delivery.instana.io/dev-sandbox-docker-all/konrad/instana-agent-operator
  newTag: konrad
