// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/k8s/object/builders/agent/secrets/containers-instana-io-secret/docker_config_json.go

// Package containers_instana_io_secret is a generated GoMock package.
package containers_instana_io_secret

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockdockerConfigMarshaler is a mock of dockerConfigMarshaler interface.
type MockdockerConfigMarshaler struct {
	ctrl     *gomock.Controller
	recorder *MockdockerConfigMarshalerMockRecorder
}

// MockdockerConfigMarshalerMockRecorder is the mock recorder for MockdockerConfigMarshaler.
type MockdockerConfigMarshalerMockRecorder struct {
	mock *MockdockerConfigMarshaler
}

// NewMockdockerConfigMarshaler creates a new mock instance.
func NewMockdockerConfigMarshaler(ctrl *gomock.Controller) *MockdockerConfigMarshaler {
	mock := &MockdockerConfigMarshaler{ctrl: ctrl}
	mock.recorder = &MockdockerConfigMarshalerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdockerConfigMarshaler) EXPECT() *MockdockerConfigMarshalerMockRecorder {
	return m.recorder
}

// MarshalOrDie mocks base method.
func (m *MockdockerConfigMarshaler) MarshalOrDie(obj *DockerConfigJson) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalOrDie", obj)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// MarshalOrDie indicates an expected call of MarshalOrDie.
func (mr *MockdockerConfigMarshalerMockRecorder) MarshalOrDie(obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalOrDie", reflect.TypeOf((*MockdockerConfigMarshaler)(nil).MarshalOrDie), obj)
}

// UnMarshalOrDie mocks base method.
func (m *MockdockerConfigMarshaler) UnMarshalOrDie(raw []byte) *DockerConfigJson {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnMarshalOrDie", raw)
	ret0, _ := ret[0].(*DockerConfigJson)
	return ret0
}

// UnMarshalOrDie indicates an expected call of UnMarshalOrDie.
func (mr *MockdockerConfigMarshalerMockRecorder) UnMarshalOrDie(raw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnMarshalOrDie", reflect.TypeOf((*MockdockerConfigMarshaler)(nil).UnMarshalOrDie), raw)
}
