apiVersion: v1
kind: Secret
metadata:
  name: instana-agent-tls
  namespace: placeholder
  ownerReferences:
    - apiVersion: apps/v1
      kind: InstanaAgent
      name: placeholder
      uid: placeholder
  labels:
    app.kubernetes.io/managed-by: instana-agent-operator
type: kubernetes.io/tls
data:
  tls.crt: placeholder
  tls.key: placeholder
