FROM registry.access.redhat.com/ubi8/ubi-minimal
MAINTAINER Instana, support@instana.com

LABEL name="instana-agent-operator" \
      vendor="Instana" \
      version="v0.0.1" \
      release="1" \
      summary="Experimental alpha version of the upcoming Kubernetes Operator for the Instana APM Agent" \
      description="This operator will deploy a daemon set to run the Instana APM Agent on each cluster node."

RUN microdnf install --nodocs java-11-openjdk-headless && microdnf clean all
COPY licenses /licenses
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
COPY target/lib/* /deployments/lib/
COPY target/*-runner.jar /deployments/app.jar
ENTRYPOINT [ "java", "-jar", "/deployments/app.jar" ]
