FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

ARG VERSION=dev
ARG BUILD=1

LABEL name="instana-agent-operator" \
      vendor="Instana" \
      version=$VERSION \
      build=$BUILD \
      summary="Beta version of the Kubernetes Operator for the Instana APM Agent" \
      description="This operator will deploy a daemon set to run the Instana APM Agent on each cluster node."

RUN microdnf install java-11-openjdk-headless && microdnf clean all
COPY licenses /licenses
COPY target/lib/* /deployments/lib/
COPY target/*-runner.jar /deployments/app.jar
ENTRYPOINT [ "java", "-jar", "/deployments/app.jar" ]
