// /*
// (c) Copyright IBM Corp. 2024
// (c) Copyright Instana Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// */
//

// Code generated by MockGen. DO NOT EDIT.
package ports

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOpenTelemetrySettings is a mock of OpenTelemetrySettings interface.
type MockOpenTelemetrySettings struct {
	ctrl     *gomock.Controller
	recorder *MockOpenTelemetrySettingsMockRecorder
}

// MockOpenTelemetrySettingsMockRecorder is the mock recorder for MockOpenTelemetrySettings.
type MockOpenTelemetrySettingsMockRecorder struct {
	mock *MockOpenTelemetrySettings
}

// NewMockOpenTelemetrySettings creates a new mock instance.
func NewMockOpenTelemetrySettings(ctrl *gomock.Controller) *MockOpenTelemetrySettings {
	mock := &MockOpenTelemetrySettings{ctrl: ctrl}
	mock.recorder = &MockOpenTelemetrySettingsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenTelemetrySettings) EXPECT() *MockOpenTelemetrySettingsMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockOpenTelemetrySettings) ISGOMOCK() struct{} {
	return struct{}{}
}

// GrpcIsEnabled mocks base method.
func (m *MockOpenTelemetrySettings) GrpcIsEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrpcIsEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GrpcIsEnabled indicates an expected call of GrpcIsEnabled.
func (mr *MockOpenTelemetrySettingsMockRecorder) GrpcIsEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrpcIsEnabled", reflect.TypeOf((*MockOpenTelemetrySettings)(nil).GrpcIsEnabled))
}

// HttpIsEnabled mocks base method.
func (m *MockOpenTelemetrySettings) HttpIsEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HttpIsEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HttpIsEnabled indicates an expected call of HttpIsEnabled.
func (mr *MockOpenTelemetrySettingsMockRecorder) HttpIsEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HttpIsEnabled", reflect.TypeOf((*MockOpenTelemetrySettings)(nil).HttpIsEnabled))
}

// IsEnabled mocks base method.
func (m *MockOpenTelemetrySettings) IsEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockOpenTelemetrySettingsMockRecorder) IsEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockOpenTelemetrySettings)(nil).IsEnabled))
}
