# permissions for end users to view instanaagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instanaagent-viewer-role
rules:
- apiGroups:
  - agents.instana.com
  resources:
  - instanaagents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agents.instana.com
  resources:
  - instanaagents/status
  verbs:
  - get
