# permissions for end users to edit instanaagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instanaagent-editor-role
rules:
- apiGroups:
  - agents.instana.com
  resources:
  - instanaagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agents.instana.com
  resources:
  - instanaagents/status
  verbs:
  - get
