#
# (c) Copyright IBM Corp. 2025
#
# This rule is not used by the project instana-agent-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the instana.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: instana-agent-operator
    app.kubernetes.io/managed-by: kustomize
  name: instanaagentremote-editor-role
rules:
- apiGroups:
  - instana.io
  resources:
  - agentsremote
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - instana.io
  resources:
  - agentsremote/status
  verbs:
  - get
