apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: instana-agent-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Defines the desired specs and states for instana agent deployment.
      displayName: Instana Agent
      kind: InstanaAgent
      name: instanaagent.agents.instana.com
      version: v1beta1
  description: APM observability
  displayName: Instana agent
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - IBM
  - Cloud
  links:
  - name: Instana Agent Operator
    url: https://instana-agent-operator.domain
  maintainers:
  - email: test
    name: test
  maturity: alpha
  provider:
    name: IBM
  version: 0.0.0
