apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: instana-agent-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Defines the desired specs and states for instana agent deployment.
      displayName: Instana Agent
      kind: InstanaAgent
      name: instanaagent.agents.instana.com
      resources:
      - kind: DaemonSet
        name: instana-agent-daemonset
        version: v1
      - kind: Pod
        name: instana-agent-pod
        version: v1
      - kind: Service
        name: instana-agent-service
        version: v1
      specDescriptors:
      - description: The name of your kubernetes cluster
        displayName: Cluster Name
        path: clusterName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'Optional: Kubernetes Cluster Role Binding Name Defaults to instana-agent'
        displayName: Cluster Role Binding Name
        path: clusterRoleBindingName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'Optional: Kubernetes Cluster Role Name Defaults to instana-agent'
        displayName: Cluster Role Name
        path: clusterRoleName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Configuration files
        displayName: Agent configuration files
        path: configFiles
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'Optional: Kubernetes ConfigMap Name Defaults to instana-agent'
        displayName: Config Map Name
        path: configMapName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'Optional: Kubernetes Daemonset Name Defaults to instana-agent-daemonset'
        displayName: Daemon Set Name
        path: daemonSetName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Instana agent download key
        displayName: Download Key
        path: downloadKey
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Set agent's endpoint
        displayName: Agent Endpoint
        path: endpoint
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Set environment vars
        displayName: Agent environment variables
        path: env
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'Optional: Instana agent host repository'
        displayName: Host Repository
        path: hostRepository
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'Optional: Instana agent image'
        displayName: Image
        path: image
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'Optional: Kubernetes Image pull policy Defaults to Always'
        displayName: Image Pull Policy
        path: imagePullPolicy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Set your Instana agent key
        displayName: Agent Key
        path: key
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Secret
      - description: 'Optional: OpenTelemetry enabled Defaults to false'
        displayName: Open Telemetry Enabled
        path: opentelemetryEnabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: 'Optional: Rbac creation Defaults to true'
        displayName: Rbac Creation
        path: rbacCreation
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: 'Optional: Define resources requests and limits for single pods'
        displayName: Resources
        path: resources
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:resourceRequirements
      - description: 'Optional: Kubernetes Secret Name Defaults to instana-agent'
        displayName: Secret Name
        path: secretName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'Optional: Kubernetes Service Account Name Defaults to instana-agent'
        displayName: Service Account Name
        path: serviceAccountName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: 'Optional: Set the zone of the host'
        displayName: Zone Name
        path: zoneName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      version: v1beta1
  description: APM observability
  displayName: Instana agent
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - IBM
  - Cloud
  - Observability
  - Instana
  links:
  - name: Instana Agent Operator
    url: https://instana-agent-operator.domain
  maintainers:
  - email: miel.donkers@instana.com
    name: Miel
  - email: henning.treu@instana.com
    name: Henning
  - email: yousef.abdelhamid@instana.com
    name: Yousef
  maturity: alpha
  provider:
    name: IBM
  version: 0.0.0
