kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - containerPath: /hosthome
        hostPath: /Users
  - role: worker
    extraMounts:
      - containerPath: /hosthome
        hostPath: /Users
  - role: worker
    extraMounts:
      - containerPath: /hosthome
        hostPath: /Users
