/*
 * (c) Copyright IBM Corp. 2025
 */

// This file provides minimal stubs to satisfy 'go mod tidy' when mocks aren't generated
// Real mocks are generated by 'make gen-mocks'

package mocks

import "go.uber.org/mock/gomock"

// Minimal stubs - just enough to satisfy imports for go mod tidy
// These will be ignored when actual mocks are generated

type MockClient struct{}
type MockClientMockRecorder struct{}
type MockSubResourceWriter struct{}
type MockSubResourceWriterMockRecorder struct{}
type MockInstanaAgentClient struct{}
type MockInstanaAgentClientMockRecorder struct{}

func NewMockClient(ctrl *gomock.Controller) *MockClient              { return &MockClient{} }
func (m *MockClient) EXPECT() *MockClientMockRecorder                { return &MockClientMockRecorder{} }
func (mr *MockClientMockRecorder) Patch(...interface{}) *gomock.Call { return &gomock.Call{} }

func NewMockSubResourceWriter(ctrl *gomock.Controller) *MockSubResourceWriter {
	return &MockSubResourceWriter{}
}
func (m *MockSubResourceWriter) EXPECT() *MockSubResourceWriterMockRecorder {
	return &MockSubResourceWriterMockRecorder{}
}
func (mr *MockSubResourceWriterMockRecorder) Update(...interface{}) *gomock.Call {
	return &gomock.Call{}
}

func NewMockInstanaAgentClient(ctrl *gomock.Controller) *MockInstanaAgentClient {
	return &MockInstanaAgentClient{}
}
func (m *MockInstanaAgentClient) EXPECT() *MockInstanaAgentClientMockRecorder {
	return &MockInstanaAgentClientMockRecorder{}
}
func (mr *MockInstanaAgentClientMockRecorder) Apply(...interface{}) *gomock.Call {
	return &gomock.Call{}
}
