apiVersion: agents.instana.com/v1beta1
kind: InstanaAgent
metadata:
  name: instana-agent
  namespace: instana-agent
spec:
  zoneName: my-zone # (optional) name of the zone of the host
  key: Mlp5a2MybV9SaUtKblZFLVROTmRyQQ== # replace with your Instana agent key
  endpoint:
    host: ingress-pink-saas.instana.rocks # the monitoring ingress endpoint
    port: "443" # the monitoring ingress endpoint port, wrapped in quotes
  env: []
  clusterName: docker-desktop # replace with the name of your Kubernetes cluster
  configFiles:
    configuration.yaml: |
      # You can leave this empty, or use this to configure your instana agent.
      # See https://docs.instana.io/setup_and_manage/host_agent/on/kubernetes/