apiVersion: instana.io/v1
kind: InstanaAgent
metadata:
  name: instana-agent
  namespace: instana-agent
spec:
  zone:
    name: edited-zone # (optional) name of the zone of the host
  cluster:
    name: my-cluster
  agent:
    key: replace-key # replace with your Instana agent key
    endpointHost: ingress-red-saas.instana.io
    endpointPort: "443"
    # URLs to dependency files that will be fetched via an init container and shared with the agent pod
    dependencyURLs:
      - "https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.28/mysql-connector-java-8.0.28.jar"
      - "https://repo1.maven.org/maven2/org/postgresql/postgresql/42.3.3/postgresql-42.3.3.jar"
    env: {}
    configuration_yaml: |
      # You can leave this empty, or use this to configure your instana agent.
      # See https://github.com/instana/instana-agent-operator/blob/main/config/samples/instana_v1_extended_instanaagent.yaml for the extended version.
  opentelemetry:
    grpc:
      enabled: true
    http:
      enabled: true

# Made with Bob
