apiVersion: instana.io/v1
kind: InstanaAgent
metadata:
  name: instana-agent
  namespace: instana-agent
spec:
  zone:
    name: edited-zone # (optional) name of the zone of the host
  cluster:
      # cluster.name represents the name that will be assigned to this cluster in Instana
      name: my-cluster
  agent:
    # replace with your Instana agent key
    key: replace-key
    # Rather than specifying the agent key and optionally the download key, you can "bring your
    # own secret" creating it in the namespace in which you install the `instana-agent` and
    # specify its name in the `keysSecret` field. The secret you create must contains
    # a field called `key` and optionally one called `downloadKey`, which contain, respectively,
    # the values you'd otherwise set in `.agent.key` and `agent.downloadKey`.
    # If you are using multiple backends, the fields in the secret should be called
    # `key`, `key-1`, `key-2`, etc for each reporting backend.
    # The order of the keys and the backends listed in additionalBackends below need to match.
    # If the keySecret is defined, the key specified for each backend is ignored.
    # keysSecret: null
    endpointHost: ingress-red-saas.instana.io
    endpointPort: "443"
    # The minimum number of seconds for which a newly created Pod should be ready without any of its containers crashing, for it to be considered available
    minReadySeconds: 0
    # use this to set additional environment variables for the instana agent
    # for example:
    # env:
    #   INSTANA_AGENT_TAGS: dev
    env: {}
    # These are additional backends the Instana agent will report to besides
    # the one configured via the `agent.endpointHost`, `agent.endpointPort` and `agent.key` setting
    additionalBackends: []
      # - endpointHost: ingress.instana.io
      #   endpointPort: 443
      #   key: <agent_key>

    # TLS for end-to-end encryption between Instana agent and clients accessing the agent.
    # The Instana agent does not yet allow enforcing TLS encryption.
    # TLS is only enabled on a connection when requested by the client.
      #    tls:
      # In order to enable TLS, a secret of type kubernetes.io/tls must be specified.
      # secretName is the name of the secret that has the relevant files.
      # secretName: ""
      # Otherwise,  the certificate and the private key must be provided as base64 encoded.
      # certificate: ""
    # key: ""

    image:
      # agent.image.name is the name of the container image of the Instana agent.
      name: icr.io/instana/agent
      # agent.image.digest is the digest (a.k.a. Image ID) of the agent container image; if specified, it has priority over agent.image.tag, which will be ignored.
      #digest:
      # agent.image.tag is the tag name of the agent container image; if agent.image.digest is specified, this property is ignored.
      tag: latest
      # agent.image.pullPolicy specifies when to pull the image container.
      pullPolicy: Always
      # agent.image.pullSecrets allows you to override the default pull secret that is created when agent.image.name starts with "containers.instana.io"
      # Setting agent.image.pullSecrets prevents the creation of the default "containers-instana-io" secret.
      # pullSecrets:
      #   - name: my_awesome_secret_instead
      # If you want no imagePullSecrets to be specified in the agent pod, you can just pass an empty array to agent.image.pullSecrets
      # pullSecrets: []

    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1

    pod:
      # agent.pod.annotations are additional annotations to be added to the agent pods.
      annotations: {}

      # agent.pod.labels are additional labels to be added to the agent pods.
      labels: {}

      # agent.pod.tolerations are tolerations to influence agent pod assignment.
      #   https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
      tolerations: []

      # agent.pod.affinity are affinities to influence agent pod assignment.
      # https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
      affinity: {}

      # agent.pod.priorityClassName is the name of an existing PriorityClass that should be set on the agent pods
      #   https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
      #      priorityClassName: ""

      # agent.pod.requests and agent.pod.limits adjusts the resource assignments for the DaemonSet agent
      #   regardless of the kubernetes.deployment.enabled setting
      requests:
        # agent.pod.requests.memory is the requested memory allocation in MiB for the agent pods.
        memory: 768Mi
        # agent.pod.requests.cpu are the requested CPU units allocation for the agent pods.
        cpu: "0.5"
      limits:
        # agent.pod.limits.memory set the memory allocation limits in MiB for the agent pods.
        memory: 768Mi
        # agent.pod.limits.cpu sets the CPU units allocation limits for the agent pods.
        cpu: "1.5"
      
      # agent.pod.volumes and agent.pod.volumeMounts are additional volumes and volumeMounts for user-specific files.
      # For example, a certificate may need to be mounted for an agent sensor to connect to the monitored target.
      # https://kubernetes.io/docs/concepts/storage/volumes/
      volumes:
        - name: my-secret-volume
          secret:
            secretName: instana-agent-key
      volumeMounts:
        - name: my-secret-volume
          mountPath: /secrets
      env:
        - name: INSTANA_AGENT_TAGS
          value: "kubernetes,example"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
        - name: CONFIG_VALUE
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: value

    serviceMesh:
      # agent.serviceMesh.enabled sets the Instana agent's communication direction with JVMs.
      # To allow communication to be directed to the agent, set this variable to true.
      enabled: true

    # agent.host.repository sets a host path to be mounted as the agent maven repository (for debugging or development purposes)
    #    host:
    #      repository: ""

    configuration_yaml: |
    # You can leave this empty, or use this to configure your instana agent.
    # See https://ibm.biz/monitoring-k8s

  # openshift specifies whether the cluster role should include openshift permissions and other tweaks to the YAML.
  # The chart will try to auto-detect if the cluster is OpenShift, so you will likely not even need to set this explicitly.
  # openshift: true

  rbac:
    # Specifies whether RBAC resources should be created
    create: true

  service:
    # Specifies whether to create the instana-agent service to expose within the cluster the Prometheus remote-write, OpenTelemetry GRCP endpoint and other APIs
    # Note: Requires Kubernetes 1.17+, as it uses topologyKeys
    create: true

  opentelemetry:
  # enabled: true # parent level setting defaults to true
   grpc:
     enabled: true # only evaluated, if parent level setting is set to true or is not defined
     port: 4317 # default port for grpc
   http:
     enabled: true # # only evaluated, if parent level setting is set to true or is not defined
     port: 4318 # default port for http
  prometheus:
    remoteWrite:
      enabled: false # If true, it will also apply `service.create=true`

  serviceAccount:
    # Specifies whether a ServiceAccount should be created
    create: true
    # The name of the ServiceAccount to use.
    # If not set and `create` is true, a name is generated using the fullname template
    # name: instana-agent
    # Annotations to add to the service account
    annotations: {}

  k8s_sensor:
    image:
      # k8s_sensor.image.name is the name of the container image of the Instana agent.
      name: icr.io/instana/k8sensor
      # k8s_sensor.image.digest is the digest (a.k.a. Image ID) of the agent container image; if specified, it has priority over agent.image.tag, which will be ignored.
      #digest:
      # k8s_sensor.image.tag is the tag name of the agent container image; if agent.image.digest is specified, this property is ignored.
      tag: latest
      # k8s_sensor.image.pullPolicy specifies when to pull the image container.
      pullPolicy: Always
    deployment:
      # Specifies whether or not to enable the Deployment and turn off the Kubernetes sensor in the DaemonSet
      enabled: true
      # Use three replicas to ensure the HA by the default.
      replicas: 3
      # The minimum number of seconds for which a newly created Pod should be ready without any of its containers crashing, for it to be considered available
      minReadySeconds: 0
      # k8s_sensor.deployment.pod adjusts the resource assignments for the agent independently of the DaemonSet agent when k8s_sensor.deployment.enabled=true
      pod:
        requests:
          # k8s_sensor.deployment.pod.requests.memory is the requested memory allocation in MiB for the agent pods.
          memory: 128Mi
          # k8s_sensor.deployment.pod.requests.cpu are the requested CPU units allocation for the agent pods.
          cpu: 120m
        limits:
          # k8s_sensor.deployment.pod.limits.memory set the memory allocation limits in MiB for the agent pods.
          memory: 2048Mi
          # k8s_sensor.deployment.pod.limits.cpu sets the CPU units allocation limits for the agent pods.
          cpu: 500m
        affinity:
          podAntiAffinity:
            # Soft anti-affinity policy: try not to schedule multiple kubernetes-sensor pods on the same node.
            # If the policy is set to "requiredDuringSchedulingIgnoredDuringExecution", if the cluster has
            # fewer nodes than the amount of desired replicas, `helm install/upgrade --wait` will not return.
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: instana/agent-mode
                    operator: In
                    values: [ KUBERNETES ]
                topologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      # Specifies whether or not to setup a pod disruption budget for the k8sensor deployment
      enabled: false

  kubernetes:
    # Configures use of a Deployment for the Kubernetes sensor rather than as a potential member of the DaemonSet. Is only accepted if k8s_sensor.deployment.enabled=false
    deployment:
      # Specifies whether or not to enable the Deployment and turn off the Kubernetes sensor in the DaemonSet
      enabled: false
      # Use a single replica, the impact will generally be low and we need to address a host of other concerns where clusters are large.
      replicas: 1
      # The minimum number of seconds for which a newly created Pod should be ready without any of its containers crashing, for it to be considered available
      minReadySeconds: 0
      # kubernetes.deployment.pod adjusts the resource assignments for the agent independently of the DaemonSet agent when kubernetes.deployment.enabled=true
      pod:
        requests:
          # kubernetes.deployment.pod.requests.memory is the requested memory allocation in MiB for the agent pods.
          memory: 1024Mi
          # kubernetes.deployment.pod.requests.cpu are the requested CPU units allocation for the agent pods.
          cpu: 720m
        limits:
          # kubernetes.deployment.pod.limits.memory set the memory allocation limits in MiB for the agent pods.
          memory: 3072Mi
          # kubernetes.deployment.pod.limits.cpu sets the CPU units allocation limits for the agent pods.
          cpu: 4

  # zones:
  # # Configure use of zones to use tolerations as the basis to associate a specific daemonset per tainted node pool
  # - name: pool-01
  #   tolerations:
  #   - key: "pool"
  #     operator: "Equal"
  #     value: "pool-01"
  #     effect: "NoExecute"
  # - name: pool-02
  #   tolerations:
  #   - key: "pool"
  #     operator: "Equal"
  #     value: "pool-02"
  #     effect: "NoExecute"