apiVersion: instana.io/v1
kind: InstanaAgentRemote
metadata:
  name: remote-agent
  namespace: "instana-agent"
spec:
  zone:
    name: edited-zone # (optional) name of the zone of the host
  agent:
    key: replace-key # replace with your Instana agent key
    endpointHost: ingress-red-saas.instana.io
    endpointPort: "443"
    env: {}
  remote_configuration_yaml: |
    # Remote Sensor Configurations
  requests: # (optional)
        # agent.pod.requests.memory is the requested memory allocation in MiB for the agent pods.
    memory: 768Mi
        # agent.pod.requests.cpu are the requested CPU units allocation for the agent pods.
    cpu: "0.5"
  limits: # (optional)
        # agent.pod.limits.memory set the memory allocation limits in MiB for the agent pods.
    memory: 768Mi
        # agent.pod.limits.cpu sets the CPU units allocation limits for the agent pods.
    cpu: "1.5"
