apiVersion: v1
kind: ServiceAccount
metadata:
  name: instana-agent
  namespace: placeholder
  ownerReferences:
    - apiVersion: apps/v1
      kind: InstanaAgent
      name: placeholder
      uid: placeholder
  labels:
    app.kubernetes.io/managed-by: instana-agent-operator
