// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/k8s/object/transformations/transformations.go

// Package daemonset is a generated GoMock package.
package daemonset

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockTransformations is a mock of Transformations interface.
type MockTransformations struct {
	ctrl     *gomock.Controller
	recorder *MockTransformationsMockRecorder
}

// MockTransformationsMockRecorder is the mock recorder for MockTransformations.
type MockTransformationsMockRecorder struct {
	mock *MockTransformations
}

// NewMockTransformations creates a new mock instance.
func NewMockTransformations(ctrl *gomock.Controller) *MockTransformations {
	mock := &MockTransformations{ctrl: ctrl}
	mock.recorder = &MockTransformationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransformations) EXPECT() *MockTransformationsMockRecorder {
	return m.recorder
}

// AddCommonLabels mocks base method.
func (m *MockTransformations) AddCommonLabels(obj client.Object) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCommonLabels", obj)
}

// AddCommonLabels indicates an expected call of AddCommonLabels.
func (mr *MockTransformationsMockRecorder) AddCommonLabels(obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCommonLabels", reflect.TypeOf((*MockTransformations)(nil).AddCommonLabels), obj)
}

// AddCommonLabelsToMap mocks base method.
func (m *MockTransformations) AddCommonLabelsToMap(labels map[string]string, name string, skipVersionLabel bool) map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCommonLabelsToMap", labels, name, skipVersionLabel)
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// AddCommonLabelsToMap indicates an expected call of AddCommonLabelsToMap.
func (mr *MockTransformationsMockRecorder) AddCommonLabelsToMap(labels, name, skipVersionLabel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCommonLabelsToMap", reflect.TypeOf((*MockTransformations)(nil).AddCommonLabelsToMap), labels, name, skipVersionLabel)
}

// AddOwnerReference mocks base method.
func (m *MockTransformations) AddOwnerReference(obj client.Object) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddOwnerReference", obj)
}

// AddOwnerReference indicates an expected call of AddOwnerReference.
func (mr *MockTransformationsMockRecorder) AddOwnerReference(obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOwnerReference", reflect.TypeOf((*MockTransformations)(nil).AddOwnerReference), obj)
}
