version: "2"

tasks:
  pr-code-checks:
    displayName: build-amd64-arm64-s390x-and-ppc64le-images
    runtimeClassName: large
    onError: stopAndFail
    include:
      - dind
    steps:
      - name: unit-test
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          source $WORKSPACE/$APP_REPO_FOLDER/ci/sps-scripts/sps-build-multiarch-images.sh
      - name: detect-secrets
        include:
          - docker-socket

  pr-code-checks-2:
    from: pr-code-checks
    displayName: build-and-test-agent-operator
    runtimeClassName: large
    onError: stopAndFail
    include:
      - dind
    steps:
      - name: unit-test
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          ./installGolang.sh 1.24.4 amd64
          export PATH=$PATH:/usr/local/go/bin
          go install
          make build
      - name: detect-secrets
        include:
          - docker-socket
    
  pr-code-checks-3:
    from: pr-code-checks
    displayName: go-lang-unit-test
    runtimeClassName: large
    onError: stopAndFail
    include:
      - dind
      - memdisk-monitor
    steps:
      - name: unit-test
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          ./installGolang.sh 1.24.4 amd64
          export PATH=$PATH:/usr/local/go/bin
          time make generate
        
          time go install

          time make test
      - name: detect-secrets
        include:
          - docker-socket
  pr-code-checks-4:
    from: pr-code-checks
    displayName: operator-olm-build
    runtimeClassName: large
    include:
      - dind
    steps:
      - name: unit-test
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          if [[ "$PIPELINE_DEBUG" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi
          export GIT_COMMIT="$(get_env branch || echo "latest")"
          export ARTIFACTORY_INTERNAL_USERNAME=$(get_env ARTIFACTORY_INTERNAL_USERNAME)
          export ARTIFACTORY_INTERNAL_PASSWORD=$(get_env ARTIFACTORY_INTERNAL_PASSWORD)

          dnf -y install microdnf
          ./installGolang.sh 1.24.4 amd64
          export PATH=$PATH:/usr/local/go/bin

          IMAGE_TAG=${GIT_COMMIT}
          echo "Using IMAGE_TAG=${IMAGE_TAG}"
          unset HISTFILE
          skopeo login -u ${ARTIFACTORY_INTERNAL_USERNAME} -p ${ARTIFACTORY_INTERNAL_PASSWORD} delivery.instana.io

          OPERATOR_IMAGE_NAME=delivery.instana.io/int-docker-agent-local/instana-agent-operator/dev-build
          OPERATOR_IMG_DIGEST=$(skopeo inspect --format "{{.Digest}}" docker://${OPERATOR_IMAGE_NAME}:${IMAGE_TAG})
          echo "OPERATOR_IMG_DIGEST=$OPERATOR_IMG_DIGEST"
 
          mkdir -p target
          mkdir -p bundle
          mkdir -p ../docker-input

          export PREFIX="v"
          export VERSION="$(cat ./version/AGENT_OPERATOR_VERSION)"
          export OLM_RELEASE_VERSION=${VERSION#"$PREFIX"}

          # Get currently published version of the OLM bundle in the community operators project, so we can correctly set the 'replaces' field
          # Uses jq to filter out non-release versions
          export PREV_VERSION=$(curl --silent --fail --show-error -L https://api.github.com/repos/instana/instana-agent-operator/tags \
            | jq 'map(select(.name | test("^v[0-9]+.[0-9]+.[0-9]+$"))) | .[1].name' \
            | sed 's/[^0-9]*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/')

          if [[ "x${PREV_VERSION}" = "x" ]]; then
              echo "!! Could not determine previous released version. Fix either pipeline or tag history !!"
              exit 1
          fi

          echo "Operator manifest SHA found, using digest ${OPERATOR_IMG_DIGEST} for Operator image"
          export OPERATOR_IMAGE="${OPERATOR_IMAGE_NAME}@${OPERATOR_IMG_DIGEST}"

          # Get the digest for the agent image
          AGENT_IMAGE_NAME="icr.io/instana/agent"
          AGENT_IMAGE_TAG="latest"
          echo "Fetching digest for ${AGENT_IMAGE_NAME}:${AGENT_IMAGE_TAG}"
          export AGENT_IMG_DIGEST=$(skopeo inspect --format "{{.Digest}}" docker://${AGENT_IMAGE_NAME}:${AGENT_IMAGE_TAG})
          echo "AGENT_IMG_DIGEST=$AGENT_IMG_DIGEST"


          # Create bundle for public operator with image: delivery.instana.io/int-docker-agent-local/instana-agent-operator/dev-build:<version>
          make IMG="${OPERATOR_IMAGE}" \
            VERSION="${OLM_RELEASE_VERSION}" \
            PREV_VERSION="${PREV_VERSION}" \
            AGENT_IMG="icr.io/instana/agent@${AGENT_IMG_DIGEST}" \
            bundle

          cp bundle.Dockerfile ../docker-input/
          cp -R bundle ../docker-input/
          pushd bundle
          zip -r ../target/olm-${OLM_RELEASE_VERSION}.zip .
          popd

          # Create the YAML for installing the Agent Operator, which we want to package with the release
          make --silent IMG="${OPERATOR_IMAGE_NAME}:${OLM_RELEASE_VERSION}" controller-yaml > target/instana-agent-operator.yaml

          echo -e "===== DISPLAYING target/instana-agent-operator.yaml =====\n"
          cat target/instana-agent-operator.yaml
      - name: detect-secrets
        include:
          - docker-socket

  pr-code-checks-5:
    from: pr-code-checks
    displayName: e2e-ocp-latest
    runtimeClassName: large
    runAfter: 
      - pr-code-checks
      - pr-code-checks-2
    include:
      - dind
    steps:
      - name: unit-test
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export GIT_COMMIT="$(get_env branch || echo "latest")"
          export CLUSTER_ID="ocp-fyre-latest"
          export TASK_NAME="pr-code-checks-5"
          source $WORKSPACE/$APP_REPO_FOLDER/ci/sps-scripts/e2e.sh
      - name: detect-secrets
        include:
          - docker-socket

  pr-code-checks-6:
    from: pr-code-checks
    displayName: e2e-gke-latest
    runtimeClassName: large
    runAfter: 
      - pr-code-checks
      - pr-code-checks-2
    include:
      - dind
    steps:
      - name: unit-test
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          export GIT_COMMIT="$(get_env branch || echo "latest")"
          export CLUSTER_ID="gke-latest"
          export SKIP_INSTALL_GCLOUD="false"
          export TASK_NAME="pr-code-checks-6"
          source $WORKSPACE/$APP_REPO_FOLDER/ci/sps-scripts/e2e.sh
      - name: detect-secrets
        include:
          - docker-socket

  pr-code-checks-7:
    from: pr-code-checks
    displayName: tag-release
    runtimeClassName: large
    runAfter: 
      - pr-code-checks-5
      - pr-code-checks-6
    include:
      - dind
    steps:
      - name: unit-test
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          source $WORKSPACE/$APP_REPO_FOLDER/ci/scripts/tag-new-release.sh
      - name: detect-secrets
        include:
          - docker-socket
  
  pr-code-checks-8:
    from: pr-code-checks
    displayName: build-multiarch-manifest
    runtimeClassName: large
    runAfter: 
      - pr-code-checks-5
      - pr-code-checks-6
    include:
      - dind
    steps:
      - name: unit-test
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3
        include:
          - docker-socket
        script: |
          #!/usr/bin/env bash
          ARTIFACTORY_INTERNAL_CREDENTIALS=$(get_env artifactory_internal)
          ARTIFACTORY_CREDENTIALS=$(get_env artifactory)
          RED_HAT_REGISTRY_CREDENTIALS=$(get_env RED_HAT_REGISTRY)
          
          export ARTIFACTORY_USERNAME_INTERNAL=$(echo "${ARTIFACTORY_INTERNAL_CREDENTIALS}" | jq -r ".username")
          export ARTIFACTORY_PASSWORD_INTERNAL=$(echo "${ARTIFACTORY_INTERNAL_CREDENTIALS}" | jq -r ".password")

          export RED_HAT_REGISTRY_USERNAME=$(echo "${RED_HAT_REGISTRY_CREDENTIALS}" | jq -r ".username")
          export RED_HAT_REGISTRY_PASSWORD=$(echo "${RED_HAT_REGISTRY_CREDENTIALS}" | jq -r ".password")

          export ARTIFACTORY_PASSWORD=$(echo "${ARTIFACTORY_CREDENTIALS}" | jq -r ".password")
          export ARTIFACTORY_PASSWORD=$(echo "${ARTIFACTORY_CREDENTIALS}" | jq -r ".password")

          DEV_BUILD_IMAGE=delivery.instana.io/int-docker-agent-local/instana-agent-operator/dev-build
          ICR_REPOSITORY=icr.io/instana/instana-agent-operator
          ARTIFACTORY_REPOSITORY="${ARTIFACTORY_CONTAINER_DOCKER_URL}/instana-agent-operator"
          RED_HAT_REGISTRY="quay.io/redhat-isv-containers/5e961c2c93604e02afa9ebdf"

          DIGEST=$(cat agent-operator-image-manifest-sha/digest)
          echo ${DIGEST}
          skopeo copy -a --preserve-digests \
            --src-username ${ARTIFACTORY_USERNAME_INTERNAL} \
            --src-password ${ARTIFACTORY_PASSWORD_INTERNAL} \
            --dest-username ${ARTIFACTORY_USERNAME} \
            --dest-password ${ARTIFACTORY_PASSWORD} \
            docker://${DEV_BUILD_IMAGE}@${DIGEST} \
            docker://${DEV_BUILD_IMAGE}:main

          # For non-public releases we are done:
          export RELEASE_REGEX='^v[0-9]+\.[0-9]+\.[0-9]+$'
          if ! [[ $VERSION =~ $RELEASE_REGEX ]]; then
            echo "---> **** Internal release, publishing to icr.io & Red Hat container registry skipped. ****"
            exit 0
          fi

          echo "---> **** Public release, publishing to icr.io & Red Hat container registry. ****"

          # strip the leading "v" from the operator version for release:
          export PREFIX="v"
          export OPERATOR_DOCKER_VERSION=${VERSION#"$PREFIX"}

          echo "---> Pushing multi-architectural manifest to icr.io with version tag"
          skopeo copy -a --preserve-digests \
            --src-username ${ARTIFACTORY_USERNAME_INTERNAL} \
            --src-password ${ARTIFACTORY_PASSWORD_INTERNAL} \
            --dest-username ${ICR_USERNAME} \
            --dest-password ${ICR_PASSWORD} \
            docker://${DEV_BUILD_IMAGE}@${DIGEST} \
            docker://${ICR_REPOSITORY}:${OPERATOR_DOCKER_VERSION}

          echo "---> Pushing multi-architectural manifest to icr.io with the latest tag"
          skopeo copy -a --preserve-digests \
            --src-username ${ARTIFACTORY_USERNAME_INTERNAL} \
            --src-password ${ARTIFACTORY_PASSWORD_INTERNAL} \
            --dest-username ${ICR_USERNAME} \
            --dest-password ${ICR_PASSWORD} \
            docker://${DEV_BUILD_IMAGE}@${DIGEST} \
            docker://${ICR_REPOSITORY}:latest

          echo "---> Pushing multi-architectural manifest to ${ARTIFACTORY_REPOSITORY}"
          skopeo copy -a --preserve-digests \
            --src-username ${ARTIFACTORY_USERNAME_INTERNAL} \
            --src-password ${ARTIFACTORY_PASSWORD_INTERNAL} \
            --dest-username ${ARTIFACTORY_USERNAME} \
            --dest-password ${ARTIFACTORY_PASSWORD} \
            docker://${DEV_BUILD_IMAGE}@${DIGEST} \
            docker://${ARTIFACTORY_REPOSITORY}:${OPERATOR_DOCKER_VERSION}

          echo "---> pushing images to Red Hat Container Registry"
          skopeo copy -a --preserve-digests \
            --src-username ${ARTIFACTORY_USERNAME_INTERNAL} \
            --src-password ${ARTIFACTORY_PASSWORD_INTERNAL} \
            --dest-username ${RED_HAT_REGISTRY_USERNAME} \
            --dest-password ${RED_HAT_REGISTRY_PASSWORD} \
            docker://${DEV_BUILD_IMAGE}@${DIGEST} \
            docker://${RED_HAT_REGISTRY}:${OPERATOR_DOCKER_VERSION}
      - name: detect-secrets
        include:
          - docker-socket


