#
# (c) Copyright IBM Corp. 2025
#
---
groups:
  - name: fedramp-promotion
    jobs:
    - self-update
    - manual-trigger
    - artifact-promotion
  - name: manual-fedramp-version-bump
    jobs:
    - bump-fedramp-minor-version

var:
  instana-operator-git-repo-config: &instana-operator-git-repo-config
    uri: https://github.com/instana/instana-agent-operator.git
    branch: main
    username: instanacd
    password: ((instanacd-github-api-token))

resource_types:
  - name: cogito
    type: registry-image
    check_every: never
    source:
      repository: icr.io/instana-int/int-docker-cogito-instana-local/cogito
      tag: latest
      username: ((icr-api-key.username))
      password: ((icr-api-key.password))

  - name: slack-notification
    type: registry-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: gh-status
    type: cogito
    source:
      owner: instana
      repo: instana-agent-operator
      access_token: ((instanacd-github-api-token))
      context_prefix: concourse
      github_host: github.com

  - name: slack-alert
    type: slack-notification
    source:
      url: ((tech-agent-delivery-notifications-slack-hook))

  - name: agent-operator-git-source
    type: git
    icon: github
    source:
      <<: *instana-operator-git-repo-config

  - name: artifactory-to-cos-mirroring
    type: git
    icon: github
    source:
      uri: https://github.ibm.com/instana/artifactory-to-cos-mirroring.git
      username: ((ibm-ghe-tokens.concourse-other-teams))
      password: x-oauth-basic
      branch: main

  - name: fedramp-version
    type: semver
    icon: alpha
    source:
      driver: gcs
      initial_version: 1.0.0
      bucket: instana-agent-qa-versioning
      key: operator/fedramp/version
      json_key: ((project-berlin-tests-gcp-instana-qa))

jobs:
  - name: bump-fedramp-minor-version
    max_in_flight: 1
    plan:
    - put: fedramp-version
      params: { bump: minor }

  - name: self-update
    on_success:
      put: gh-status
      inputs: [ agent-operator-git-source ]
      params: { state: success, context: self-update }
    on_failure:
      do:
        - put: slack-alert
          params:
            channel: '#tech-agent-delivery-notifications'
            text: |
              :x: the operator fedramp self-update has failed. <!subteam^SNMD75GH3> please check <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|the build job>.
        - put: gh-status
          inputs: [ agent-operator-git-source ]
          params: { state: failure, context: self-update }
    on_error:
      do:
        - put: slack-alert
          params:
            channel: '#tech-agent-delivery-notifications'
            text: |
              :x: the operator fedramp self-update has failed. <!subteam^SNMD75GH3> please check <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|the build job>.
        - put: gh-status
          inputs: [ agent-operator-git-source ]
          params: { state: error, context: self-update }
    on_abort:
      put: gh-status
      inputs: [ agent-operator-git-source ]
      params: { state: error, context: self-update }
    plan:
      - get: agent-operator-git-source
        trigger: true
      - put: gh-status
        inputs: [ agent-operator-git-source ]
        params: { state: pending, context: self-update }
      - put: gh-status
        inputs: [ agent-operator-git-source ]
        params: { state: pending, context: self-update }
      - set_pipeline: self
        file: agent-operator-git-source/ci/fedramp-promotion-pipeline.yaml

  - name: manual-trigger
    max_in_flight: 1
    plan:
      - get: agent-operator-git-source
      - get: fedramp-version
  
  - name: artifact-promotion
    on_success:
      do: 
      - put: gh-status
        inputs: [ agent-operator-git-source ]
        params: { state: success, context: artifact-promotion }
      - put: fedramp-version
        params: { bump: patch }
    on_failure:
      do:
        - put: slack-alert
          params:
            channel: '#tech-agent-delivery-notifications'
            text: |
              :x: the operator fedramp artifact-promotion has failed. <!subteam^SNMD75GH3> please check <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|the build job>.
        - put: gh-status
          inputs: [ agent-operator-git-source ]
          params: { state: failure, context: artifact-promotion }
    on_error:
      do:
        - put: slack-alert
          params:
            channel: '#tech-agent-delivery-notifications'
            text: |
              :x: the operator fedramp artifact-promotion has failed. <!subteam^SNMD75GH3> please check <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|the build job>.
        - put: gh-status
          inputs: [ agent-operator-git-source ]
          params: { state: error, context: artifact-promotion }
    on_abort:
      put: gh-status
      inputs: [ agent-operator-git-source ]
      params: { state: error, context: artifact-promotion }
    max_in_flight: 1
    plan:
      - get: agent-operator-git-source
        passed: [manual-trigger]
        trigger: true
      - get: fedramp-version
        passed: [manual-trigger]
      - get: artifactory-to-cos-mirroring
      - task: promote-artifacts
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: icr.io/instana-int/int-docker-agent-local/instana-agent-operator/e2e-test-base-image
              tag: main
              username: ((icr-api-key.username))
              password: ((icr-api-key.password))
          params:
            ARTIFACTORY_USERNAME_RELEASE: ((delivery-instana-io-release-project-artifact-read-writer-creds.username))
            ARTIFACTORY_PASSWORD_RELEASE: ((delivery-instana-io-release-project-artifact-read-writer-creds.password))
            ARTIFACTORY_BASE_URL: ((delivery-artifactory-base-url))
            ARTIFACTORY_CONTAINER_DOCKER_URL: ((delivery-artifactory-docker-agent-release-url))
            ARTIFACTORY_CONTAINER_FEDRAMP_DOCKER_URL: ((delivery-artifactory-docker-agent-fedramp-url))
            ARTIFACTORY_GENERIC_FEDRAMP_URL: ((delivery-artifactory-generic-agent-fedramp-url))
            ARTIFACTORY_TAAS_USERNAME: ((taas-artifactory-read-writer-creds.username))
            ARTIFACTORY_TAAS_PASSWORD: ((taas-artifactory-read-writer-creds.password))
            ICR_USERNAME: ((icr-api-key.username))
            ICR_PASSWORD: ((icr-api-key.password))
          inputs:
            - name: agent-operator-git-source
            - name: fedramp-version
          run:
            path: /bin/bash
            args:
              - -c
              - |
                #!/bin/bash

                RELEASE_ICR_REPOSITORY="icr.io/instana/instana-agent-operator"
                FEDRAMP_ARTIFACTORY_REPOSITORY="${ARTIFACTORY_CONTAINER_FEDRAMP_DOCKER_URL}/instana-agent-operator"
                FEDRAMP_ICR_REPOSITORY="icr.io/instana-rel/rel-docker-agent-fedramp-local/instana-agent-operator"

                DOMAIN=$(echo $ARTIFACTORY_GENERIC_FEDRAMP_URL | cut -d'/' -f1)
                echo $DOMAIN
                REPO_PATH=$(echo $ARTIFACTORY_GENERIC_FEDRAMP_URL | cut -d'/' -f2-)
                FEDRAMP_GENERIC="$DOMAIN/artifactory/$REPO_PATH"
                FEDRAMP_GENERIC_REPOSITORY="${FEDRAMP_GENERIC}/instana-agent-operator"
                FEDRAMP_GENERIC_REPOSITORY_TAAS="na.artifactory.swg-devops.com/artifactory/instana-team-release-agent-fedramp-generic-local/instana-agent-operator"

                export ARTIFACT_VERSION
                pushd agent-operator-git-source
                  source ./ci/scripts/get-latest-fedramp-release-version.sh
                popd
                FEDRAMP_VERSION=$(cat fedramp-version/number)

                # Check if ARTIFACT_VERSION is set
                if [ -z "$ARTIFACT_VERSION" ]; then
                  echo "Error: ARTIFACT_VERSION is not set. Failed to get the latest FedRAMP release version."
                  exit 1
                fi

                # Check if FEDRAMP_VERSION is set
                if [ -z "$FEDRAMP_VERSION" ]; then
                  echo "Error: FEDRAMP_VERSION is not set. Failed to read version from fedramp-version/number."
                  exit 1
                fi

                # strip the leading "v" from the operator version for release:
                export PREFIX="v"
                export OPERATOR_DOCKER_VERSION=${ARTIFACT_VERSION#"$PREFIX"}
                COMBINED_VERSION=${OPERATOR_DOCKER_VERSION}.fedramp-${FEDRAMP_VERSION}

                # Validate OPERATOR_DOCKER_VERSION before using it
                if [ -z "$OPERATOR_DOCKER_VERSION" ]; then
                  echo "Error: OPERATOR_DOCKER_VERSION is not set. Cannot proceed with artifact promotion."
                  exit 1
                fi

                # Validate COMBINED_VERSION before using it
                if [ -z "$COMBINED_VERSION" ]; then
                  echo "Error: COMBINED_VERSION is not set. Cannot proceed with artifact promotion."
                  exit 1
                fi

                echo "Using OPERATOR_DOCKER_VERSION=$OPERATOR_DOCKER_VERSION and COMBINED_VERSION=$COMBINED_VERSION"

                echo "---> Pushing multi-architectural manifest to ${FEDRAMP_ARTIFACTORY_REPOSITORY}"
                skopeo copy -a --preserve-digests \
                  --src-username ${ARTIFACTORY_USERNAME_RELEASE} \
                  --src-password ${ARTIFACTORY_PASSWORD_RELEASE} \
                  --dest-username ${ARTIFACTORY_USERNAME_RELEASE} \
                  --dest-password ${ARTIFACTORY_PASSWORD_RELEASE} \
                  docker://${RELEASE_ICR_REPOSITORY}:${OPERATOR_DOCKER_VERSION} \
                  docker://${FEDRAMP_ARTIFACTORY_REPOSITORY}:${COMBINED_VERSION}
                
                echo "---> Pushing multi-architectural manifest to ${FEDRAMP_ARTIFACTORY_REPOSITORY} with latest tag"
                skopeo copy -a --preserve-digests \
                  --src-username ${ARTIFACTORY_USERNAME_RELEASE} \
                  --src-password ${ARTIFACTORY_PASSWORD_RELEASE} \
                  --dest-username ${ARTIFACTORY_USERNAME_RELEASE} \
                  --dest-password ${ARTIFACTORY_PASSWORD_RELEASE} \
                  docker://${RELEASE_ICR_REPOSITORY}:${OPERATOR_DOCKER_VERSION} \
                  docker://${FEDRAMP_ARTIFACTORY_REPOSITORY}:latest

                echo "---> Pushing multi-architectural manifest to ${FEDRAMP_ICR_REPOSITORY}"
                skopeo copy -a --preserve-digests \
                  --src-username ${ARTIFACTORY_USERNAME_RELEASE} \
                  --src-password ${ARTIFACTORY_PASSWORD_RELEASE} \
                  --dest-username ${ICR_USERNAME} \
                  --dest-password ${ICR_PASSWORD} \
                  docker://${RELEASE_ICR_REPOSITORY}:${OPERATOR_DOCKER_VERSION} \
                  docker://${FEDRAMP_ICR_REPOSITORY}:${COMBINED_VERSION}

                echo "---> Pushing multi-architectural manifest to ${FEDRAMP_ICR_REPOSITORY} with latest tag"
                skopeo copy -a --preserve-digests \
                  --src-username ${ARTIFACTORY_USERNAME_RELEASE} \
                  --src-password ${ARTIFACTORY_PASSWORD_RELEASE} \
                  --dest-username ${ICR_USERNAME} \
                  --dest-password ${ICR_PASSWORD} \
                  docker://${RELEASE_ICR_REPOSITORY}:${OPERATOR_DOCKER_VERSION} \
                  docker://${FEDRAMP_ICR_REPOSITORY}:latest
                
                echo "Pull the released manifest and replace icr.io image with FedRAMP artifactory image"
                VERSION=${OPERATOR_DOCKER_VERSION} COMBINED_VERSION=${COMBINED_VERSION} ./agent-operator-git-source/ci/scripts/fedramp-manifest-converter.sh

                MANIFEST_FILE_FEDRAMP="instana-agent-operator.yaml"
                echo "Verify the size of the instana-agent-operator.yaml before pushing"
                if [ -s $MANIFEST_FILE_FEDRAMP ]; then
                  echo "File exists and it's not empty"
                else
                  echo "Download failed or file is empty. Aborting"
                  exit 1
                fi

                echo "---> Pushing operator YAML to ${FEDRAMP_GENERIC_REPOSITORY} with $COMBINED_VERSION"
                status_code=$(curl --silent --output /dev/stderr --write-out "%{http_code}" -u "${ARTIFACTORY_USERNAME_RELEASE}:${ARTIFACTORY_PASSWORD_RELEASE}" -X PUT "https://$FEDRAMP_GENERIC_REPOSITORY/$COMBINED_VERSION/instana-agent-operator.yaml" -T "${MANIFEST_FILE_FEDRAMP}")
                echo # curl doesn't output a line break on error
                if test "$status_code" -ne 201; then
                  echo -e "[\e[1m\e[91mERROR\e[39m\e[21m] curl returned $status_code, exiting..."
                  exit 1
                fi


                echo "---> Pushing operator YAML to ${FEDRAMP_GENERIC_REPOSITORY} with latest"
                status_code=$(curl --silent --output /dev/stderr --write-out "%{http_code}" -u "${ARTIFACTORY_USERNAME_RELEASE}:${ARTIFACTORY_PASSWORD_RELEASE}" -X PUT "https://$FEDRAMP_GENERIC_REPOSITORY/latest/instana-agent-operator.yaml" -T "${MANIFEST_FILE_FEDRAMP}")
                echo # curl doesn't output a line break on error
                if test "$status_code" -ne 201; then
                  echo -e "[\e[1m\e[91mERROR\e[39m\e[21m] curl returned $status_code, exiting..."
                  exit 1
                fi

                echo "---> Pushing operator YAML to ${FEDRAMP_GENERIC_REPOSITORY_TAAS} with $COMBINED_VERSION"
                status_code=$(curl --silent --output /dev/stderr --write-out "%{http_code}" -u "${ARTIFACTORY_TAAS_USERNAME}:${ARTIFACTORY_TAAS_PASSWORD}" -X PUT "https://$FEDRAMP_GENERIC_REPOSITORY_TAAS/$COMBINED_VERSION/instana-agent-operator.yaml" -T "${MANIFEST_FILE_FEDRAMP}")
                echo # curl doesn't output a line break on error
                if test "$status_code" -ne 201; then
                  echo -e "[\e[1m\e[91mERROR\e[39m\e[21m] curl returned $status_code, exiting..."
                  exit 1
                fi


                echo "---> Pushing operator YAML to ${FEDRAMP_GENERIC_REPOSITORY_TAAS} with latest"
                status_code=$(curl --silent --output /dev/stderr --write-out "%{http_code}" -u "${ARTIFACTORY_TAAS_USERNAME}:${ARTIFACTORY_TAAS_PASSWORD}" -X PUT "https://$FEDRAMP_GENERIC_REPOSITORY_TAAS/latest/instana-agent-operator.yaml" -T "${MANIFEST_FILE_FEDRAMP}")
                echo # curl doesn't output a line break on error
                if test "$status_code" -ne 201; then
                  echo -e "[\e[1m\e[91mERROR\e[39m\e[21m] curl returned $status_code, exiting..."
                  exit 1
                fi
      - task: sync-fedramp-artifacts-to-cos
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: registry.access.redhat.com/ubi9/ubi
              tag: latest
          params:
            API_URL: ((artifactory-mirror-api-key.url))
            API_BASIC_AUTH_USERNAME: ((artifactory-mirror-api-key.username))
            API_BASIC_AUTH_PASSWORD: ((artifactory-mirror-api-key.password))
          inputs:
            - name: artifactory-to-cos-mirroring
          run:
            path: /bin/bash
            args:
              - -c
              - |
                set -e
                yum install -y jq
                
                # Remove trailing slash from API_URL to prevent double slashes in URLs
                export API_URL="${API_URL%/}"

                REPO="instana-team-release-agent-fedramp-generic-virtual"
                PATH_PREFIX="instana-agent-operator"
                echo "Syncing ${REPO} (path: ${PATH_PREFIX}) to COS..."
                
                if artifactory-to-cos-mirroring/util/trigger-sync-and-wait.sh "${REPO}" --path-prefix "${PATH_PREFIX}"; then
                  echo "SUCCESS: COS sync completed for ${REPO}/${PATH_PREFIX}"
                  exit 0
                fi
                
                echo "WARNING: First sync attempt failed, retrying once..."
                sleep 5
                
                if artifactory-to-cos-mirroring/util/trigger-sync-and-wait.sh "${REPO}" --path-prefix "${PATH_PREFIX}"; then
                  echo "SUCCESS: COS sync completed on retry for ${REPO}/${PATH_PREFIX}"
                  exit 0
                fi
                
                echo "ERROR: COS sync failed after retry for ${REPO}/${PATH_PREFIX}"
                echo "Artifacts are available in Artifactory but not yet mirrored to COS"
                echo "Please trigger manual sync: ./util/trigger-sync-and-wait.sh ${REPO} --path-prefix ${PATH_PREFIX}"
                exit 1
