---
aliases:
  gh-status-hooks: &gh-status-hooks
    on_success:
      put: gh-status
      inputs: [ instana-agent-operator ]
      params: { state: success }
    on_failure:
      put: gh-status
      inputs: [ instana-agent-operator ]
      params: { state: failure }
    on_error:
      put: gh-status
      inputs: [ instana-agent-operator ]
      params: { state: error }
    on_abort:
      put: gh-status
      inputs: [ instana-agent-operator ]
      params: { state: error }
  gh-status-set-pending: &gh-status-set-pending
    put: gh-status
    inputs: [ instana-agent-operator ]
    params: { state: pending }
  gh-status-set-pending-build: &gh-status-set-pending-build
    put: gh-status
    inputs: [ instana-agent-operator ]
    params: { state: pending, context: build-and-test-operator/build }
  gh-status-set-pending-unit-test: &gh-status-set-pending-unit-test
    put: gh-status
    inputs: [ instana-agent-operator ]
    params: { state: pending, context: build-and-test-operator/unit-test }

var:

  instana-operator-git-repo-config: &instana-operator-git-repo-config
    uri: https://github.com/instana/instana-agent-operator.git
    username: ((project-berlin-gh-token))
    password: x-oauth-basic
    branch: &build-branch ((branch))
    git_config:
      - name: user.name
        value: Stan
      - name: user.email
        value: stan@instana.com
resource_types:

  - name: cogito
    type: registry-image
    check_every: never
    source:
      repository: delivery.instana.io/int-docker-cogito-instana-local/cogito
      tag: latest
      username: ((delivery-instana-io-internal-project-artifact-read-writer-creds.username))
      password: ((delivery-instana-io-internal-project-artifact-read-writer-creds.password))

resources:

  - name: pipeline-source
    type: git
    icon: github
    source:
      <<: *instana-operator-git-repo-config

  - name: instana-agent-operator
    type: git
    icon: github
    source:
      <<: *instana-operator-git-repo-config

  - name: gh-status
    type: cogito
    source:
      owner: instana
      repo: instana-agent-operator
      access_token: ((instanacd-github-api-token))
      context_prefix: concourse
      github_host: github.com
  
  - name: golangci-lint-release
    type: github-release
    check_every: 24h
    source:
      owner: golangci
      repository: golangci-lint

jobs:

  - name: self-update
    <<: *gh-status-hooks
    max_in_flight: 1
    plan:
      - get: instana-agent-operator
      - <<: *gh-status-set-pending
      - get: pipeline-source
        trigger: true
      - set_pipeline: self
        file: pipeline-source/ci/pr-pipeline.yml
        vars:
          branch: *build-branch
          project-berlin-gh-token: ((project-berlin-gh-token))
          delivery-instana-io-release-project-artifact-read-writer-creds: ((delivery-instana-io-release-project-artifact-read-writer-creds))

  - name: build-and-test-agent-operator
    max_in_flight: 1
    plan:
      - get: pipeline-source
        trigger: true
        passed: [self-update]
      - get: instana-agent-operator
      - <<: *gh-status-set-pending-build
      - <<: *gh-status-set-pending-unit-test
      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: registry.access.redhat.com/ubi8/ubi-minimal
          inputs:
            - name: pipeline-source
          run:
            path: bash
            args:
              - -ceu
              - |
                cd pipeline-source
                microdnf install make python3-devel gcc git tar gzip zip curl jq
                pip3 install pyyaml
                
                export PATH="$PATH:/usr/local/go/bin"
                export GOPATH=/go
                export GO_VERSION=1.22.3
                export GO_SHA256="8920ea521bad8f6b7bc377b4824982e011c19af27df88a815e3586ea895f1b36 go${GO_VERSION}.linux-amd64.tar.gz"
                curl -L --fail --show-error --silent "https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz" -o "go${GO_VERSION}.linux-amd64.tar.gz" \
                && echo "${GO_SHA256}" | sha256sum --check \
                && rm -rf /usr/local/go \
                && tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz" \
                && mkdir -p "${GOPATH}" \
                && go version
                make build
        on_success:
          put: gh-status
          inputs: [ instana-agent-operator ]
          params: { state: success, context: build-and-test-operator/build }
          on_failure:
            put: gh-status
            inputs: [ instana-agent-operator ]
            params: { state: failure, context: build-and-test-operator/build }
          on_error:
            put: gh-status
            inputs: [ instana-agent-operator ]
            params: { state: error, context: build-and-test-operator/build }
          on_abort:
            put: gh-status
            inputs: [ instana-agent-operator ]
            params: { state: error, context: build-and-test-operator/build }
      - get: golangci-lint-release
        params:
          globs:
          - golangci-lint-*-linux-amd64.rpm
      - task: unit-test
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: registry.access.redhat.com/ubi8/ubi-minimal
          inputs:
            - name: pipeline-source
            - name: golangci-lint-release
          caches:
            - path: /go/pkg/mod
          run:
            path: bash
            args:
              - -ceu
              - |
                microdnf install make python3-devel gcc git tar gzip zip curl jq
                pip3 install pyyaml
                
                pushd golangci-lint-release
                LINTER_RPM=$(ls golangci-lint-*-linux-amd64.rpm)
                rpm -i $LINTER_RPM
                popd
                
                cd pipeline-source
                export PATH="$PATH:/usr/local/go/bin"
                export GOPATH=/go
                export GO_VERSION=1.22.1
                curl -L --fail --show-error --silent "https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz" -o "go${GO_VERSION}.linux-amd64.tar.gz" \
                && rm -rf /usr/local/go \
                && tar -C /usr/local -xzf "go${GO_VERSION}.linux-amd64.tar.gz" \
                && mkdir -p "${GOPATH}" \
                && go version
                make lint test
        on_success:
          put: gh-status
          inputs: [ instana-agent-operator ]
          params: { state: success, context: build-and-test-operator/unit-test }
        on_failure:
          put: gh-status
          inputs: [ instana-agent-operator ]
          params: { state: failure, context: build-and-test-operator/unit-test }
        on_error:
          put: gh-status
          inputs: [ instana-agent-operator ]
          params: { state: error, context: build-and-test-operator/unit-test }
        on_abort:
          put: gh-status
          inputs: [ instana-agent-operator ]
          params: { state: error, context: build-and-test-operator/unit-test }
