---

resources:
  - name: agent-operator-pipeline-source
    type: git
    icon: github
    source:
      uri: https://github.com/instana/instana-agent-operator.git
      branch: main

  - name: instana-agent-operator-release
    type: github-release
    check_every: 5m
    source:
      owner: instana
      repository: instana-agent-operator

  - name: yq-release
    type: github-release
    check_every: 24h
    source:
      owner: mikefarah
      repository: yq

  - name: community-operators-repo
    type: git
    icon: github
    source:
      uri: https://github.com/instana/community-operators.git
      branch: main
      username: instanacd
      password: ((instanacd-github-api-token))
  - name: certified-operators-repo
    type: git
    icon: github
    source:
      uri: https://github.com/instana/certified-operators.git
      branch: main
      username: instanacd
      password: ((instanacd-github-api-token))
  - name: redhat-marketplace-operators-repo
    type: git
    icon: github
    source:
      uri: https://github.com/instana/redhat-marketplace-operators.git
      branch: main
      username: instanacd
      password: ((instanacd-github-api-token))

jobs:
  - name: self-update
    max_in_flight: 1
    plan:
      - get: agent-operator-pipeline-source
        trigger: true
      - set_pipeline: self
        file: agent-operator-pipeline-source/ci/rh-olm-release-pipeline.yaml

  - name: olm-release-pr-creation
    max_in_flight: 1
    plan:
      - get: instana-agent-operator-release
        params:
          globs:
            - olm-*.zip
        trigger: true
      - in_parallel:
          steps:
            - do:
                - get: community-operators-repo
                - task: community-operator-commit-changes
                  config:
                    platform: linux
                    image_resource:
                      type: registry-image
                      source:
                        repository: registry.access.redhat.com/ubi8/ubi-minimal
                    inputs:
                      - name: instana-agent-operator-release
                      - name: community-operators-repo
                    outputs:
                      - name: community-operators-repo
                    params:
                      GH_API_TOKEN: ((instanacd-github-api-token))
                      OWNER: k8s-operatorhub
                      REPO: community-operators
                    run:
                      path: bash
                      args:
                        - -ce
                        - |
                          microdnf install git zip curl jq
                          
                          pushd instana-agent-operator-release
                          
                          OLM_BUNDLE_ZIP=$(ls olm*.zip)
                          OPERATOR_RELEASE_VERSION=$(echo $OLM_BUNDLE_ZIP | sed 's/olm-\(.*\)\.zip/\1/')
                          COMMIT_MESSAGE="operator instana-agent-operator ($OPERATOR_RELEASE_VERSION)"
                          OLM_BUNDLE_ZIP_PATH="$(pwd)/$OLM_BUNDLE_ZIP"
                          
                          echo "Check if the PR is already open"
                          PR_LIST_JSON=$(curl -fH "Accept: application/vnd.github+json" https://api.github.com/repos/$OWNER/$REPO/pulls)
                          EXISTING_PR_INFO_JSON=$(echo $PR_LIST_JSON | jq ".[] | select(.title==\"$COMMIT_MESSAGE\")")
                          if [ ! -z "$EXISTING_PR_INFO_JSON" ]; then
                            echo "PR already exists, exiting"
                            exit 0
                          fi
                          echo "PR does not exist, creating a PR"

                          popd
                          
                          pushd community-operators-repo/operators/instana-agent-operator
                          set -x
                          git pull -r

                          mkdir -p $OPERATOR_RELEASE_VERSION
                          unzip -o $OLM_BUNDLE_ZIP_PATH -d $OPERATOR_RELEASE_VERSION
                          
                          git config --global user.name "instanacd"
                          git config --global user.email "instanacd@instana.com"
                          
                          git add .
                          git commit -s -m "$COMMIT_MESSAGE" --allow-empty
                          
                          popd
                - put: community-operators-repo
                  params:
                    repository: community-operators-repo
                - task: community-operator-create-pr
                  config:
                    platform: linux
                    image_resource:
                      type: registry-image
                      source:
                        repository: registry.access.redhat.com/ubi8/ubi-minimal
                    inputs:
                      - name: instana-agent-operator-release
                      - name: community-operators-repo
                    params:
                      GH_API_TOKEN: ((instanacd-github-api-token))
                      OWNER: k8s-operatorhub
                      REPO: community-operators
                    run:
                      path: bash
                      args:
                        - -ce
                        - |
                          microdnf install curl jq
                          
                          pushd instana-agent-operator-release

                          OLM_BUNDLE_ZIP=$(ls olm*.zip)
                          OPERATOR_RELEASE_VERSION=$(echo $OLM_BUNDLE_ZIP | sed 's/olm-\(.*\)\.zip/\1/')
                          COMMIT_MESSAGE="operator instana-agent-operator ($OPERATOR_RELEASE_VERSION)"
                          OLM_BUNDLE_ZIP_PATH="$(pwd)/$OLM_BUNDLE_ZIP"

                          echo "Check if the PR is already open"
                          PR_LIST_JSON=$(curl -fH "Accept: application/vnd.github+json" https://api.github.com/repos/$OWNER/$REPO/pulls)
                          EXISTING_PR_INFO_JSON=$(echo $PR_LIST_JSON | jq ".[] | select(.title==\"$COMMIT_MESSAGE\")")
                          if [ ! -z "$EXISTING_PR_INFO_JSON" ]; then
                            echo "PR already exists, exiting"
                            exit 0
                          fi
                          echo "PR does not exist, creating a PR"

                          popd
                          
                          # Create the PR
                          set -x
                          curl \
                            -fX POST \
                            -H "Accept: application/vnd.github+json" \
                            -H "Authorization: Bearer $GH_API_TOKEN" \
                            https://api.github.com/repos/$OWNER/$REPO/pulls \
                            -d "{\"title\":\"$COMMIT_MESSAGE\",\"head\":\"instana:main\",\"base\":\"main\"}"

            - do:
                - get: certified-operators-repo
                - task: certified-operator-commit-changes
                  config:
                    platform: linux
                    image_resource:
                      type: registry-image
                      source:
                        repository: registry.access.redhat.com/ubi8/ubi-minimal
                    inputs:
                      - name: instana-agent-operator-release
                      - name: certified-operators-repo
                    outputs:
                      - name: certified-operators-repo
                    params:
                      GH_API_TOKEN: ((instanacd-github-api-token))
                      OWNER: redhat-openshift-ecosystem
                      REPO: certified-operators
                    run:
                      path: bash
                      args:
                        - -ce
                        - |
                          microdnf install git zip curl jq
                          
                          pushd instana-agent-operator-release
                          
                          OLM_BUNDLE_ZIP=$(ls olm*.zip)
                          OPERATOR_RELEASE_VERSION="v$(echo $OLM_BUNDLE_ZIP | sed 's/olm-\(.*\)\.zip/\1/')"
                          COMMIT_MESSAGE="operator instana-agent-operator ($OPERATOR_RELEASE_VERSION)"
                          OLM_BUNDLE_ZIP_PATH="$(pwd)/$OLM_BUNDLE_ZIP"
                          
                          echo "Check if the PR is already open"
                          PR_LIST_JSON=$(curl -fH "Accept: application/vnd.github+json" https://api.github.com/repos/$OWNER/$REPO/pulls)
                          EXISTING_PR_INFO_JSON=$(echo $PR_LIST_JSON | jq ".[] | select(.title==\"$COMMIT_MESSAGE\")")
                          if [ ! -z "$EXISTING_PR_INFO_JSON" ]; then
                            echo "PR already exists, exiting"
                            exit 0
                          fi
                          echo "PR does not exist, creating a PR"
                          
                          popd
                          
                          pushd certified-operators-repo/operators/instana-agent-operator
                          set -x
                          git pull -r
                          mkdir -p $OPERATOR_RELEASE_VERSION
                          unzip -o $OLM_BUNDLE_ZIP_PATH -d $OPERATOR_RELEASE_VERSION
                          
                          git config --global user.name "instanacd"
                          git config --global user.email "instanacd@instana.com"
                          
                          git add .
                          git commit -s -m "$COMMIT_MESSAGE" --allow-empty
                          
                          popd
                - put: certified-operators-repo
                  params:
                    repository: certified-operators-repo
                - task: certified-operator-create-pr
                  config:
                    platform: linux
                    image_resource:
                      type: registry-image
                      source:
                        repository: registry.access.redhat.com/ubi8/ubi-minimal
                    inputs:
                      - name: instana-agent-operator-release
                      - name: certified-operators-repo
                    params:
                      GH_API_TOKEN: ((instanacd-github-api-token))
                      OWNER: redhat-openshift-ecosystem
                      REPO: certified-operators
                    run:
                      path: bash
                      args:
                        - -ce
                        - |
                          microdnf install curl jq
                          
                          pushd instana-agent-operator-release

                          OLM_BUNDLE_ZIP=$(ls olm*.zip)
                          OPERATOR_RELEASE_VERSION="v$(echo $OLM_BUNDLE_ZIP | sed 's/olm-\(.*\)\.zip/\1/')"
                          COMMIT_MESSAGE="operator instana-agent-operator ($OPERATOR_RELEASE_VERSION)"
                          OLM_BUNDLE_ZIP_PATH="$(pwd)/$OLM_BUNDLE_ZIP"

                          echo "Check if the PR is already open"
                          PR_LIST_JSON=$(curl -fH "Accept: application/vnd.github+json" https://api.github.com/repos/$OWNER/$REPO/pulls)
                          EXISTING_PR_INFO_JSON=$(echo $PR_LIST_JSON | jq ".[] | select(.title==\"$COMMIT_MESSAGE\")")
                          if [ ! -z "$EXISTING_PR_INFO_JSON" ]; then
                            echo "PR already exists, exiting"
                            exit 0
                          fi
                          echo "PR does not exist, creating a PR"

                          popd
                          set -x
                          # Create the PR
                          curl \
                            -fX POST \
                            -H "Accept: application/vnd.github+json" \
                            -H "Authorization: Bearer $GH_API_TOKEN" \
                            https://api.github.com/repos/$OWNER/$REPO/pulls \
                            -d "{\"title\":\"$COMMIT_MESSAGE\",\"head\":\"instana:main\",\"base\":\"main\"}"

            - do:
                - get: redhat-marketplace-operators-repo
                - get: yq-release
                  params:
                    globs:
                      - yq_linux_amd64
                - task: redhat-marketplace-operator-commit-changes
                  config:
                    platform: linux
                    image_resource:
                      type: registry-image
                      source:
                        repository: registry.access.redhat.com/ubi8/ubi-minimal
                    inputs:
                      - name: instana-agent-operator-release
                      - name: redhat-marketplace-operators-repo
                      - name: yq-release
                    outputs:
                      - name: redhat-marketplace-operators-repo
                    params:
                      GH_API_TOKEN: ((instanacd-github-api-token))
                      OWNER: redhat-openshift-ecosystem
                      REPO: redhat-marketplace-operators
                    run:
                      path: bash
                      args:
                        - -ce
                        - |
                          microdnf install git zip curl jq
                          
                          pushd yq-release
                          
                          chmod +x yq_linux_amd64
                          mv yq_linux_amd64 /usr/local/bin/yq
                          
                          popd
                          
                          pushd instana-agent-operator-release
                          
                          OLM_BUNDLE_ZIP=$(ls olm*.zip)
                          OPERATOR_RELEASE_VERSION="v$(echo $OLM_BUNDLE_ZIP | sed 's/olm-\(.*\)\.zip/\1/')"
                          COMMIT_MESSAGE="operator instana-agent-operator-rhmp ($OPERATOR_RELEASE_VERSION)"
                          OLM_BUNDLE_ZIP_PATH="$(pwd)/$OLM_BUNDLE_ZIP"
                          
                          echo "Check if the PR is already open"
                          PR_LIST_JSON=$(curl -fH "Accept: application/vnd.github+json" https://api.github.com/repos/$OWNER/$REPO/pulls)
                          EXISTING_PR_INFO_JSON=$(echo $PR_LIST_JSON | jq ".[] | select(.title==\"$COMMIT_MESSAGE\")")
                          if [ ! -z "$EXISTING_PR_INFO_JSON" ]; then
                            echo "PR already exists, exiting"
                            exit 0
                          fi
                          echo "PR does not exist, creating a PR"
                          
                          popd
                          
                          pushd redhat-marketplace-operators-repo/operators/instana-agent-operator-rhmp
                          set -x
                          git pull -r
                          
                          mkdir -p $OPERATOR_RELEASE_VERSION
                          unzip -o $OLM_BUNDLE_ZIP_PATH -d $OPERATOR_RELEASE_VERSION
                          
                          pushd $OPERATOR_RELEASE_VERSION
                          
                          pushd manifests
                          yq -i '.metadata.annotations += {"marketplace.openshift.io/remote-workflow": "https://marketplace.redhat.com/en-us/operators/instana-agent-operator-rhmp/pricing?utm_source=openshift_console"}' instana-agent-operator.clusterserviceversion.yaml
                          yq -i '.metadata.annotations += {"marketplace.openshift.io/support-workflow": "https://marketplace.redhat.com/en-us/operators/instana-agent-operator-rhmp/support?utm_source=openshift_console"}' instana-agent-operator.clusterserviceversion.yaml
                          mv instana-agent-operator.clusterserviceversion.yaml instana-agent-operator-rhmp.clusterserviceversion.yaml
                          popd
                          
                          pushd metadata
                          yq -i '.annotations."operators.operatorframework.io.bundle.package.v1" |= "instana-agent-operator-rhmp"' annotations.yaml
                          popd
                          
                          popd
                          
                          git config --global user.name "instanacd"
                          git config --global user.email "instanacd@instana.com"
                          
                          git add .
                          git commit -s -m "$COMMIT_MESSAGE" --allow-empty
                          
                          popd
                - put: redhat-marketplace-operators-repo
                  params:
                    repository: redhat-marketplace-operators-repo
                - task: redhat-marketplace-operator-create-pr
                  config:
                    platform: linux
                    image_resource:
                      type: registry-image
                      source:
                        repository: registry.access.redhat.com/ubi8/ubi-minimal
                    inputs:
                      - name: instana-agent-operator-release
                      - name: redhat-marketplace-operators-repo
                    params:
                      GH_API_TOKEN: ((instanacd-github-api-token))
                      OWNER: redhat-openshift-ecosystem
                      REPO: redhat-marketplace-operators
                    run:
                      path: bash
                      args:
                        - -ce
                        - |
                          microdnf install curl jq
                          
                          pushd instana-agent-operator-release

                          OLM_BUNDLE_ZIP=$(ls olm*.zip)
                          OPERATOR_RELEASE_VERSION="v$(echo $OLM_BUNDLE_ZIP | sed 's/olm-\(.*\)\.zip/\1/')"
                          COMMIT_MESSAGE="operator instana-agent-operator-rhmp ($OPERATOR_RELEASE_VERSION)"
                          OLM_BUNDLE_ZIP_PATH="$(pwd)/$OLM_BUNDLE_ZIP"

                          echo "Check if the PR is already open"
                          PR_LIST_JSON=$(curl -fH "Accept: application/vnd.github+json" https://api.github.com/repos/$OWNER/$REPO/pulls)
                          EXISTING_PR_INFO_JSON=$(echo $PR_LIST_JSON | jq ".[] | select(.title==\"$COMMIT_MESSAGE\")")
                          if [ ! -z "$EXISTING_PR_INFO_JSON" ]; then
                            echo "PR already exists, exiting"
                            exit 0
                          fi
                          echo "PR does not exist, creating a PR"

                          popd
                          set -x
                          # Create the PR
                          curl \
                            -fX POST \
                            -H "Accept: application/vnd.github+json" \
                            -H "Authorization: Bearer $GH_API_TOKEN" \
                            https://api.github.com/repos/$OWNER/$REPO/pulls \
                            -d "{\"title\":\"$COMMIT_MESSAGE\",\"head\":\"instana:main\",\"base\":\"main\"}"
