apiVersion: v1
kind: Namespace
metadata:
  name: instana-agent
  labels:
    app.kubernetes.io/name: instana-agent-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: instana-agent-operator
  namespace: instana-agent
  labels:
    app.kubernetes.io/name: instana-agent-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instana-agent-operator
  namespace: instana-agent
  labels:
    app.kubernetes.io/name: instana-agent-operator
rules:
# -------------------------------------------------------------------------
# The following are the resources created by the operator,
# the operator needs to list, watch, and create these resources.
# -------------------------------------------------------------------------
- apiGroups:
  - ''
  - 'extensions'
  - 'apps'
  - 'rbac.authorization.k8s.io'
  resources:
  - 'serviceaccounts'
  - 'clusterroles'
  - 'clusterrolebindings'
  - 'secrets'
  - 'configmaps'
  - 'daemonsets'
  verbs:
  - 'list'
  - 'watch'
  - 'create'
# -------------------------------------------------------------------------
# The following need to be watched, but not created:
# * Pods are created by the daemon set.
# * The custom resource definition is created by the user.
# -------------------------------------------------------------------------
- apiGroups:
  - ''
  - 'apiextensions.k8s.io'
  resources:
  - 'pods'
  - 'customresourcedefinitions'
  verbs:
  - 'list'
  - 'watch'
# -------------------------------------------------------------------------
# Events are just created but not watched. It's a fire-and-forget operation.
# -------------------------------------------------------------------------
- apiGroups:
  - ''
  resources:
  - 'events'
  verbs:
  - 'create'
# -------------------------------------------------------------------------
# For the custom resource, the operator needs list, watch, get, update.
# -------------------------------------------------------------------------
- apiGroups:
  - 'instana.io'
  resources:
  - 'agents'
  verbs:
  - 'get'
  - 'update'
  - 'list'
  - 'watch'
# -------------------------------------------------------------------------
# Below are the permissions are for the agent.
# The operator needs these permissions to create the agent's cluster role.
# -------------------------------------------------------------------------
- apiGroups:
  - ''
  resources:
  - 'componentstatuses'
  - 'endpoints'
  - 'events'
  - 'namespaces'
  - 'nodes'
  - 'pods'
  - 'replicationcontrollers'
  - 'resourcequotas'
  - 'services'
  - 'persistentvolumes'
  - 'persistentvolumeclaims'
verbs:
  - 'get'
  - 'list'
  - 'watch'
- apiGroups:
  - ''
  resources:
  - 'endpoints'
  verbs:
  - 'create'
  - 'update'
  - 'patch'
- apiGroups:
  - 'apps'
  resources:
  - 'deployments'
  - 'replicasets'
  - 'daemonsets'
  - 'statefulsets'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
- apiGroups:
  - 'batch'
  resources:
  - 'jobs'
  - 'cronjobs'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
- apiGroups:
  - 'extensions'
  resources:
  - 'deployments'
  - 'ingresses'
  - 'replicasets'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
- apiGroups:
  - 'networking.k8s.io'
  resources:
    - 'ingresses'
  verbs:
    - 'get'
    - 'list'
    - 'watch'
- apiGroups:
  - "apps.openshift.io"
  resources:
  - "deploymentconfigs"
  verbs:
  - "get"
  - "list"
  - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: instana-agent-operator
  labels:
    app.kubernetes.io/name: instana-agent-operator
subjects:
- kind: ServiceAccount
  name: instana-agent-operator
  namespace: instana-agent
roleRef:
  kind: ClusterRole
  name: instana-agent-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: agents.instana.io
  namespace: instana-agent
  labels:
    app.kubernetes.io/name: instana-agent-operator
spec:
  group: instana.io
  scope: Namespaced
  version: v1beta1
  names:
    plural: agents
    singular: agent
    kind: InstanaAgent
    shortNames:
    - ia
  versions:
  - name: v1beta1
    served: true
    storage: true
  - name: v1alpha1
    served: true
    storage: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: instana-agent-operator
  namespace: instana-agent
  labels:
    app.kubernetes.io/name: instana-agent-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: instana-agent-operator
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: instana-agent-operator
    spec:
      serviceAccountName: instana-agent-operator
      containers:
      - image: instana/instana-agent-operator
        name: instana-agent-operator
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: TARGET_NAMESPACES
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['olm.targetNamespaces']
