operator_version=2.2.14
operator_digest=sha256:8bcfb873a8b7741766ce3a70551541fd5ca9d6f3c144346d1c1b9d8987693141
operator_source=icr.io/instana/instana-agent-operator:latest
operator_destination=icr.io/instana-airgap-mirror/instana-agent-operator
agent_version=1.320.3
agent_digest=sha256:ffae7e9c629316f7caa8f9d4a75caf5561d2d2915e0f988119d0fdb7e74360fc
agent_source=containers.instana.io/instana/release/agent/static:latest
agent_destination=icr.io/instana-airgap-mirror/agent
k8sensor_version=1.4.16
k8sensor_digest=sha256:e541cc7a2dacd2a5b48338b2cd6dc99e5665cea197e79dab61a79b32db596b37
k8sensor_source=icr.io/instana/k8sensor:latest
k8sensor_destination=icr.io/instana-airgap-mirror/k8sensor
