apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agents.instana.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        url: https://localhost:9443/convert
        service:
          namespace: system
          name: webhook-service
          path: /convert
          $patch: delete
      conversionReviewVersions: ["v1","v1beta1"]
